# Generated by Django 3.1.7 on 2021-03-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=200, unique=True)),
                ('patient_name', models.CharField(max_length=200)),
                ('phone_mobile', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('date_of_test', models.CharField(max_length=200)),
                ('lab_number', models.CharField(max_length=200)),
                ('clinic_code', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('ref_range', models.CharField(max_length=200)),
                ('finding', models.CharField(max_length=200)),
                ('result_state', models.CharField(max_length=200)),
            ],
        ),
    ]
